# Generated by Django 3.1.1 on 2020-10-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=120)),
                ('Last_Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=100)),
                ('Username', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
                ('Confirm_Password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=120)),
                ('Password', models.CharField(max_length=25)),
                ('Full_Name', models.CharField(max_length=120)),
                ('DOB', models.DateField()),
                ('Last_Degree', models.CharField(max_length=120)),
                ('Profile_picture', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
