# Generated by Django 3.1.1 on 2020-10-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Profile_picture',
            new_name='Profile_Picture',
        ),
    ]
