# Generated by Django 3.1.1 on 2020-10-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0002_auto_20201010_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
