# Generated by Django 3.1.1 on 2020-10-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0003_resume_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
