# Generated by Django 3.1.1 on 2020-10-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0005_auto_20201010_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='DOB',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='resume',
            name='Email',
            field=models.CharField(max_length=120),
        ),
    ]
